# Generated by Django 4.1.7 on 2023-05-19 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_displayusergroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='displayusergroup',
            name='username',
        ),
    ]
